language: swift
osx_image: xcode9
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - bundle update
  - bundle exec pod update
install: true
script:
script:
  - set -o pipefail && xcodebuild test -workspace LocalizationExample.xcworkspace -scheme LocalizationExample -sdk iphonesimulator11.0 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash)