language: objective-c
osx_image: xcode9.1
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
install: true
script:
  - set -o pipefail
  - xcodebuild -workspace LocalizationExample.xcworkspace -scheme "LocalizationExample" -destination "OS=11.1,name=iPhone 8" build | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)